///////////////////////////////////////////////////////////
//  User.cs
//  Implementation of the Class User
//  Generated by Enterprise Architect
//  Created on:      12-Dec-2020 4:19:34 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

[DataContract]
public class User {

	private string ip;
	private string port;
	private string username;

	public User(){

	}

	public User(string ip, string port, string username)
	{
		this.ip = ip;
		this.port = port;
		this.username = username;
	}

	~User(){

	}

	[DataMember]
	public string Ip { get => ip; set => ip = value; }
	[DataMember]
	public string Port { get => port; set => port = value; }
	[DataMember]
	public string Username { get => username; set => username = value; }
}//end User