///////////////////////////////////////////////////////////
//  IAESSecurity.cs
//  Implementation of the Interface IAESSecurity
//  Generated by Enterprise Architect
//  Created on:      12-Dec-2020 4:19:34 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


public interface IAESSecurity  {

	/// 
	/// <param name="cyphertext"></param>
	/// <param name="key"></param>
	string Decrypt(string cyphertext, string key);

    /// 
    /// <param name="plaintext"></param>
    /// <param name="key"></param>
    string Encrypt(string plaintext, string key);
}//end IAESSecurity