///////////////////////////////////////////////////////////
//  ICentralAuthServer.cs
//  Implementation of the Interface ICentralAuthServer
//  Generated by Enterprise Architect
//  Created on:      12-Dec-2020 4:19:34 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;

[ServiceContract]
public interface ICentralAuthServer  {

	/// 
	/// <param name="ip"></param>
	/// <param name="port"></param>
    [OperationContract]
	void Authenticate(string ip, string port);
    [OperationContract]
    void RequestCertificate();
    [OperationContract]
    List<User> GetAllUsers();
    [OperationContract]
    void RevocateCertificate();
}//end ICentralAuthServer