///////////////////////////////////////////////////////////
//  IClient.cs
//  Implementation of the Interface IClient
//  Generated by Enterprise Architect
//  Created on:      12-Dec-2020 4:19:34 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;

[ServiceContract]
public interface IClient  {

    /// 
    /// <param name="message"></param>
    [OperationContract]
    void SendMessage(string message);

    /// 
    /// <param name="message"></param>
    [OperationContract]
    void SendCommunicationRequest(string ownIP, string port, string ownUserName);
}//end IClient